env:
  global:
    - CC_TEST_REPORTER_ID=75527409781ee1f93da1d4a4d4a5682db0376734ff5f54cacad070238f56f633

sudo: false

language: go

go:
  - 1.10.x
  - 1.11.x

os:
  - linux
  - osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get github.com/mattn/goveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./cc-test-reporter; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter before-build; fi

script:
  - go vet -all ./...
  - go test -race -v -coverprofile=c.out
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $GOPATH/bin/goveralls -service=travis-ci; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
